package me.gm.cleaner.client.ui

/**
 * 诊断包抓取和分享工具。
 */
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.ParcelFileDescriptor
import android.util.Log
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.core.content.FileProvider
import androidx.fragment.app.Fragment
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import me.gm.cleaner.BuildConfig
import me.gm.cleaner.R
import me.gm.cleaner.client.CleanerClient
import me.gm.cleaner.client.OrchestratedLayerStatus
import me.gm.cleaner.client.OrchestratedRuntimeStatus
import java.io.File
import java.io.FileOutputStream
import java.util.concurrent.TimeUnit
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

fun Fragment.exportDiagnosticsArchiveAndShare(context: Context) {
    AlertDialog.Builder(context)
        .setTitle(R.string.diagnostics_archive_privacy_title)
        .setMessage(R.string.diagnostics_archive_privacy_message)
        .setNegativeButton(android.R.string.cancel, null)
        .setPositiveButton(R.string.diagnostics_archive_privacy_confirm) { _, _ ->
            createDiagnosticsArchiveAndShare(context)
        }
        .show()
}

private fun Fragment.createDiagnosticsArchiveAndShare(context: Context) {
    lifecycleScope.launch(Dispatchers.IO) {
        try {
            cleanupOldDiagnosticArchives(context)
            val logFile = File(
                context.cacheDir,
                "material-cleaner-diagnostics-${System.currentTimeMillis()}.zip"
            )
            val pfd = runCatching { CleanerClient.service?.openDiagnosticsArchive() }
                .onFailure {
                    if (BuildConfig.DEBUG) Log.w("CleanerTest", "server diagnostics unavailable", it)
                }
                .getOrNull()
            if (pfd != null) {
                copyFromServerArchive(pfd, logFile)
            } else {
                createFallbackArchive(logFile)
            }
            val uri = FileProvider.getUriForFile(
                context, "${context.packageName}.fileprovider", logFile
            )
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/zip"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            withContext(Dispatchers.Main) {
                context.startActivity(
                    Intent.createChooser(intent, context.getString(R.string.share_diagnostics_archive))
                )
            }
        } catch (e: Exception) {
            if (BuildConfig.DEBUG) Log.e("CleanerTest", "diagnostics archive export failed", e)
            withContext(Dispatchers.Main) {
                Toast.makeText(
                    context,
                    "${context.getString(R.string.diagnostics_archive_failed)} ${e.message}",
                    Toast.LENGTH_SHORT
                ).show()
            }
        }
    }
}

private fun copyFromServerArchive(pfd: ParcelFileDescriptor, target: File) {
    ParcelFileDescriptor.AutoCloseInputStream(pfd).use { input ->
        FileOutputStream(target).use { output ->
            input.copyTo(output)
        }
    }
    if (target.length() == 0L) {
        throw IllegalStateException("diagnostics archive is empty")
    }
}

private fun createFallbackArchive(target: File) {
    ZipOutputStream(FileOutputStream(target)).use { zip ->
        val status = runCatching { CleanerClient.getOrchestratedStatus() }
            .getOrNull()
        addTextEntry(zip, "privacy.txt", fallbackPrivacyNotice())
        addTextEntry(zip, "manifest.txt", buildFallbackManifest())
        addTextEntry(zip, "summary_zh-CN.txt", buildFallbackSummaryZhCn(status))
        addCommandEntry(
            zip,
            "logs/app_logcat_threadtime_recent.txt",
            listOf("logcat", "-d", "-v", "threadtime", "-b", "main,system,crash", "-t", "2000")
        )
        addTextEntry(zip, "status/app_visible_status.txt", status?.toString() ?: "server unavailable")
    }
}

private fun fallbackPrivacyNotice(): String = buildString {
    appendLine("This fallback diagnostics package was generated by the app process.")
    appendLine("It may include device details, app-visible logcat output,")
    appendLine("and the app-visible service status.")
    appendLine("Basic identifiers such as build fingerprint, APK source paths,")
    appendLine("and long hex-like tokens are redacted before export.")
}

private fun buildFallbackSummaryZhCn(status: OrchestratedRuntimeStatus?): String = buildString {
    appendLine("Material Cleaner 诊断包概览（App fallback）")
    appendLine("生成时间：${System.currentTimeMillis()}")
    appendLine()
    appendLine("说明：")
    appendLine("- 这是服务端诊断不可用时由 App 进程生成的 fallback 诊断包。")
    appendLine("- 数据范围比完整服务端诊断包小，主要包含 App 可见状态和近期 logcat。")
    appendLine("- logs/app_logcat_threadtime_recent.txt：App 进程可抓取的近期日志。")
    appendLine("- status/app_visible_status.txt：App 通过 Binder 读取到的服务状态。")
    appendLine()
    appendLine("连接状态：")
    appendLine("- serverConnected=${CleanerClient.service != null}")
    appendLine("- serverVersion=${CleanerClient.serverVersion}")
    if (status == null) {
        appendLine("- orchestratedStatus=unavailable")
    } else {
        appendLine("- health=${status.health}")
        appendFallbackLayerSummary("VFS", status.vfs)
        appendFallbackLayerSummary("MediaProvider Java Hook", status.mediaProviderJavaHook)
        appendFallbackLayerSummary("FUSE Native Hook", status.fuseNativeHook)
        appendFallbackLayerSummary("DataBus", status.dataBus)
        appendFallbackLayerSummary("控制面", status.controlPlane)
    }
    appendLine()
    appendLine("如果需要完整链路证据，请优先修复服务端连接后重新导出诊断包。")
}

private fun StringBuilder.appendFallbackLayerSummary(
    label: String,
    layer: OrchestratedLayerStatus,
) {
    val error = layer.lastError.orEmpty()
    val suffix = if (error.isBlank() || error == "null") "" else "，错误=$error"
    appendLine("- $label：${layer.state}$suffix")
}

private fun buildFallbackManifest(): String = buildString {
    appendLine("createdAt=${System.currentTimeMillis()}")
    appendLine("redacted=true")
    appendLine("source=app-fallback")
    appendLine("serverConnected=${CleanerClient.service != null}")
    appendLine("serverVersion=${CleanerClient.serverVersion}")
    appendLine("sdk=${Build.VERSION.SDK_INT}")
    appendLine("release=${Build.VERSION.RELEASE}")
    appendLine("manufacturer=${Build.MANUFACTURER}")
    appendLine("brand=${Build.BRAND}")
    appendLine("model=${Build.MODEL}")
    appendLine("device=${Build.DEVICE}")
    appendLine("fingerprint=${Build.FINGERPRINT}")
}

private fun addCommandEntry(zip: ZipOutputStream, entryName: String, command: List<String>) {
    val result = runCommand(command)
    addTextEntry(zip, entryName, buildString {
        appendLine("$ ${command.joinToString(" ")}")
        appendLine("exitCode=${result.exitCode}")
        appendLine("timedOut=${result.timedOut}")
        appendLine()
        append(result.output)
    })
}

private fun runCommand(command: List<String>): CommandResult {
    var process: Process? = null
    return try {
        process = ProcessBuilder(command)
            .redirectErrorStream(true)
            .start()
        val finished = process.waitFor(10, TimeUnit.SECONDS)
        val output = process.inputStream.bufferedReader().readText()
        if (!finished) {
            process.destroyForcibly()
        }
        CommandResult(
            exitCode = if (finished) process.exitValue() else -1,
            timedOut = !finished,
            output = output,
        )
    } catch (e: Exception) {
        CommandResult(-1, timedOut = false, output = e.stackTraceToString())
    } finally {
        process?.destroy()
    }
}

private fun addTextEntry(zip: ZipOutputStream, entryName: String, content: String) {
    zip.putNextEntry(ZipEntry(entryName))
    zip.write(redact(content).toByteArray(Charsets.UTF_8))
    zip.closeEntry()
}

private fun redact(content: String): String {
    var redacted = content
    val fingerprint = Build.FINGERPRINT
    if (fingerprint.isNotBlank()) {
        redacted = redacted.replace(fingerprint, "<build-fingerprint>")
    }
    redacted = redacted
        .replace(Regex("/data/app/[^\\s\\n\\r]+"), "/data/app/<redacted>")
        .replace(Regex("/mnt/expand/[0-9A-Fa-f-]+"), "/mnt/expand/<volume>")
        .replace(Regex("(?i)\\b[0-9a-f]{24,}\\b"), "<hex-id>")
    return redacted
}

private fun cleanupOldDiagnosticArchives(context: Context) {
    context.cacheDir.listFiles()
        ?.filter { it.isFile && it.name.startsWith("material-cleaner-diagnostics-") }
        ?.sortedByDescending { it.lastModified() }
        ?.drop(3)
        ?.forEach { it.delete() }
}

private data class CommandResult(
    val exitCode: Int,
    val timedOut: Boolean,
    val output: String,
)
