plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    compileSdk rootProject.ext.compileSdk
    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        buildConfigField 'int', 'VERSION_CODE', "${rootProject.ext.versionCode}"
    }
    compileOptions {
        sourceCompatibility rootProject.ext.javaVersion
        targetCompatibility rootProject.ext.javaVersion
    }
    namespace 'me.gm.cleaner.core.config'
    buildFeatures { buildConfig true }
}

dependencies {
    implementation "androidx.core:core-ktx:$rootProject.coreVersion"
    implementation "androidx.lifecycle:lifecycle-common:$rootProject.lifecycleVersion"
    implementation "androidx.preference:preference-ktx:$rootProject.preferenceVersion"
    api "androidx.security:security-crypto-ktx:$rootProject.securityCryptoVersion"
}
