plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    compileSdk rootProject.ext.compileSdk
    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
    }
    compileOptions {
        sourceCompatibility rootProject.ext.javaVersion
        targetCompatibility rootProject.ext.javaVersion
    }
    namespace 'me.gm.cleaner.runtime.server'
    buildFeatures { buildConfig true }
}

dependencies {
    implementation "androidx.annotation:annotation:$rootProject.annotationVersion"
    implementation "androidx.core:core-ktx:$rootProject.coreVersion"
}
